name: Update RONPA Sitemap

on:
  schedule:
    - cron: "17 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-sitemap:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate sitemap
        run: python update_sitemap.py

      - name: Save sitemap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add sitemap.xml

          if git diff --cached --quiet; then
            echo "No sitemap changes"
          else
            git commit -m "Update sitemap"
            git push
          fi
